#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Write your code here
    hour = int(s[:2])
    minutes = s[3:5]
    seconds = s[6:8]
    meridian = s[-2:]
    
    if meridian == 'AM':
        if hour == 12:
            hour = 0
        else:
            return s
    else:
        if hour != 12:
            hour += 12
        
    return f"{hour:02d}:{minutes}:{seconds}"
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()

